name: esc_pos_bluetooth
description: The library allows to print receipts using an ESC/POS thermal Bluetooth printer.
# version: 0.4.1
# homepage: https://github.com/andrey-ushakov/esc_pos_bluetooth

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: 
  esc_pos_utils_plus: ^2.0.4
  # esc_pos_utils:
  # path: ../esc_pos_utils
  flutter_bluetooth_basic:
    git: 
      url: https://github.com/Netesh5/flutter_bluetooth_basic.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter


